repository:
  name: regulib
  description: "📚 Library of common Android utilities, including data manipulation & async utils."
  topics: android, android-library, gradle, maven, maven-central, kotlin, library, utilities
